# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_SENSOR=y
CONFIG_BME680=y # enable driver for BME680 gas sensor

CONFIG_GPIO=y

# for debugging purposes
CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_LORA=y
CONFIG_LORAWAN=y
CONFIG_LORAWAN_REGION_EU868=y
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y

# UART for GPS module
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# I2C1 for gas sensors
CONFIG_I2C=y

# floating point support (for formatting FP numbers to strings)
CONFIG_CBPRINTF_FP_SUPPORT=y

# to extract hardware ID, DevEUI-64 etc
CONFIG_HWINFO=y

# Increase system workqueue stack to allow Semtech soft secure-element
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
# Enable Semtech software Secure Element implementation for LoRaMac-node
CONFIG_HAS_SEMTECH_SOFT_SE=y
