name: Build Zephyr Project

on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs: 
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/zephyr-build:latest
      options: --user root

    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v4
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build Zephyr Blinky sample
        env:
          # Dem Docker-Container mitteilen, wo das vorinstallierte Zephyr liegt
          ZEPHYR_BASE: /workspaces/zephyr
        run: |
          west init -l /workspaces/zephyr
          west build -b qemu_cortex_m3 /workspaces/zephyr/samples/basic/blinky