name: Build Zephyr Project

on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs: 
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/zephyr-build:latest
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Setup Zephyr and west environment
        run: |
          west init 
          west update
          west zephyr-export
          cd zephyr
          west sdk install
      
      - name: Build Zephyr Blinky Sample Project
        run: |
          west build -b nucleo_wl55jc zephyr/samples/basic/blinky