name: Build Zephyr Project

on: 
  push:
    branches: [ master ]
    paths:
      - software/app/src/**
      - software/app/prj.conf
      - software/app/boards/nucleo_wl55jc.overlay
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Enable TMate debugging'
        required: false
        default: false

jobs: 
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci-base:main
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Zephyr and west environment
        run: |
          west init 
          west update
          west zephyr-export
          cd zephyr
          west sdk install
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      
      - name: Build zephyr project
        run: |
          west build -b nucleo_wl55jc software/app