name: Static Code Analysis

on:
  push:
    branches: [ master ]
  # enable manual workflow execution from the Actions tab in GitHub
  workflow-dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Cppcheck
        run: |
          sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run Static Analysis
        run: |
          # --force: ignores #include from Zephyr
          # --inline-suppr: suppress warnings in C code
          # --error-exitcode=1: pipeline blinks red if cppcheck finds any issues
          cppcheck --enable=warning,performance,portability --inline-suppr --force --error-exitcode=1 software/app/src/