name: Static Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    # official container of the Zephyr project
    container:
      image: ghcr.io/zephyrproject-rtos/zephyr-build:latest
      options: --user root

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Linter Tools
        run: |
          # install clang for linting
          sudo apt-get update && sudo apt-get install -y clang-tidy

      - name: Initialize West Workspace
        run: |
          cd software
          west init -l . || true
          west update

      - name: Generate Compilation Database
        env:
          ZEPHYR_BASE: /workspaces/zephyr
        run: |
          # generate compile_commands.json for the desired board
          west build -b nucleo_wl55jc -- -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run Clang-Tidy Linter
        run: |
          run-clang-tidy -p build/ "src/.*\.c$"
